### ISSUE TITLE
Simplify manual starting of the mock server

### ISSUE THREAD

**Issue by cburgmer** [realestate-com-au/pact#80] opened 2015-05-15 06:50 UTC
We are using pact with our unit test suite that we speed up using https://github.com/grosser/parallel_tests and tests are run in parallel using 8 threads.

We had to play around with pact a bit to make it work with instances fired up in parallel. Here is what we came up with, we'd be happy to have this go into documentation/a feature to make the setup more transparent. The difficulty basically was finding out how to start up pact's mock server from within RSpec runs.

```
Pact.service_consumer "our_consumer" do
  has_pact_with "our_producer" do
    mock_service :producer_service do
      port 3000
      standalone true
    end
  end
end

if ParallelTests.first_process?
  mockServiceThread = Thread.new do
    Pact::MockService::Run.call(port: 3000, log: 'log/pact.log')
  end
end

at_exit do
  if ParallelTests.first_process?
    ParallelTests.wait_for_other_processes_to_finish

    mockServiceThread.kill
  end
end
```

There's an issue left: we can't make WEBrick shut up, so it will print out three lines on startup when running rspec.

**Comment by bethesque** [comment] 2015-05-15 07:11
Interesting. Given that the mock service is stateful, how to you stop multiple pact tests using the mock service at the same time?

**Comment by bethesque** [comment] 2015-05-15 07:31
For the next release, I've added handling for webrick_options so you can do

```ruby
Pact::MockService::Run.call(port: 3000, log: 'log/pact.log', webbrick_options: {:Logger => WEBrick::Log.new(StringIO.new)})
```

**Comment by cburgmer** [comment] 2015-05-15 07:35
Good point. We plan on using different provider state between tests. Our expectation is that we would be able to separate test setup for different tests. Although we feel we might need to dig a bit deeper to understand how pact's design supports that.

Independent of that - is the recording process atomic in such a way that parallel requests coming in from different tests all get recorded?

**Comment by bethesque** [comment] 2015-05-17 21:38
That's not going to work. The original mock server was designed to only support serial tests. The interactions are all put in the same pool, and are verified from the same pool, so if you have two tests that run at the same time, setting up, tearing down and verifying from the same pool, it will get hella confused. "Provider states" aren't something that the mock service understands, that's for the provider verification. To the mock service, that's just a string on the payload that it just passes through to the pact.

Fortunately, I did some work to support parallelisation for the javascript DSL that was written using the ruby mock server. You will need to start a control server in your first thread (poke around in the pact-mock_service codebase and you'll find it), and to run a separate mock service on a separate port for each thread. The ruby library has not been modified to use this yet, however, it should not be too much work.

**Comment by bethesque** [comment] 2015-05-17 22:26
Actually, on further thought, I don't think even that is going to work, because I've just realised that the work that I did for the Javascript DSL was not to allow parallelisation, it was to allow dynamic port use rather than hardcoded ports. It would take a bit of a rewrite to allow parallel tests. How many pact tests do you have? If you're using Pact for long running UI tests, then you might be able to use a different testing strategy, and use Pact for short running unit tests instead. https://github.com/realestate-com-au/pact/wiki/Best-practices#use-pact-for-isolated-unit-tests-think-carefully-about-how-you-use-it-for-integrated-tests

**Comment by cburgmer** [comment] 2015-05-18 05:40
Got that. Thanks for the detailed answer.

Our problem is actually not about many and/or slow tests, but trying to integrate pact into existing infrastructure. So far all our existing tests are run in parallel and we were planning to integrate the new pact tests seamlessly. 

Judging by your answer this does not seem like the way forward - at least for now - and so we went ahead and added a special step to our build that runs pact tests sequentially after the main test suite.

My main take away probably is that pact's assumption of the mock server integrating transparently into any build does not hold true in 100% of the cases. But then running rspec in parallel might be a pretty particular requirement in itself.

**Comment by bethesque** [comment] 2015-05-18 06:34
You're the first people to raise it, I don't think it's terribly common to run Ruby tests in parallel. It can be done if enough people want it, but I'll wait until it's got more people asking for it, or until someone wants to put in the work before investing more time in it.

**Comment by cburgmer** [comment] 2015-05-18 06:41
Good with us. Thanks for your time, much appreciated!

**Comment by bethesque** [comment] 2015-05-24 23:07
Closing.

**Closed** 2015-06-16 05:32 UTC
